spring.application.name=exchange.point

# Data source configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/accounting
spring.datasource.username=postgres
spring.datasource.password=stab4k502

#Hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true


#for work http methods: PUT, PATCH, DELETE
spring.mvc.hiddenmethod.filter.enabled=true

#project settings
overdue_days=10